apiVersion: v1
kind: Service

metadata:
  name: bug-tracker-service

spec:
  type: NodePort

  selector:
    app: bug-tracker

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007